create extension if not exists "pgcrypto";

create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text default '',
  org_type text not null default 'government' check (org_type in ('party', 'government', 'school')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists positions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text,
  description text default '',
  org_type text not null default 'government' check (org_type in ('party', 'government', 'school')),
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists neighborhoods (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text,
  description text default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists staff (
  id bigint generated by default as identity primary key,
  staff_code text unique,
  full_name text not null,
  department_id bigint references departments(id) on delete set null,
  position_id bigint references positions(id) on delete set null,
  party_department_id bigint references departments(id) on delete set null,
  party_position_id bigint references positions(id) on delete set null,
  school_department_id bigint references departments(id) on delete set null,
  school_position_id bigint references positions(id) on delete set null,
  neighborhood_id bigint references neighborhoods(id) on delete set null,
  phone text default '',
  email text default '',
  status text not null default 'active' check (status in ('active', 'inactive')),
  notes text default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text not null default 'staff' check (role in ('admin', 'staff', 'viewer')),
  staff_id bigint references staff(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  content text default '',
  org_type text not null default 'all' check (org_type in ('party', 'government', 'school', 'all')),
  participant_department_ids jsonb not null default '[]'::jsonb,
  participant_position_ids jsonb not null default '[]'::jsonb,
  participant_neighborhood_ids jsonb not null default '[]'::jsonb,
  meeting_date date not null,
  meeting_time time not null,
  meeting_end_time time,
  location text not null,
  created_by bigint references users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references meetings(id) on delete cascade,
  staff_id bigint not null references staff(id) on delete cascade,
  checkin_time timestamptz not null default timezone('utc', now()),
  checkin_method text not null default 'qr' check (checkin_method in ('qr', 'manual', 'self')),
  status text not null check (status in ('present', 'late', 'absent')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (meeting_id, staff_id)
);

create index if not exists idx_staff_department_id on staff(department_id);
create index if not exists idx_staff_position_id on staff(position_id);
create index if not exists idx_staff_party_department_id on staff(party_department_id);
create index if not exists idx_staff_party_position_id on staff(party_position_id);
create index if not exists idx_staff_school_department_id on staff(school_department_id);
create index if not exists idx_staff_school_position_id on staff(school_position_id);
create index if not exists idx_staff_neighborhood_id on staff(neighborhood_id);
create index if not exists idx_attendance_meeting_id on attendance(meeting_id);
create index if not exists idx_attendance_staff_id on attendance(staff_id);
